# Кисельов Ілля, ІА-401, Дисципліна "Теорія прийняття рішень"

# Завантаження необхідних бібліотек для аналізу даних та асоціативних правил
library(tidyverse) # Бібліотека для зручної роботи з даними
library(knitr) # Бібліотека для створення звітів
library(arules) # Бібліотека для видобутку асоціативних правил
library(arulesViz) # Бібліотека для візуалізації асоціативних правил

# Створення списку, що представляє перегляди YouTube для різних користувачів
youtube_views <- list(
  c("Time Management for Students", "Unboxing Weird Tech Gadgets", "Як скласти ЗНО з математики на 200", "Cooking Vlog: Homemade Lasagna", "iPhone 15 Review: Is It Worth It?", "Інтерв’ю з Іваном Марчуком", "Vlog: Hiking in the Alps"),
  c("Як навчитися програмувати з нуля", "Top 10 Places to Visit in Europe", "Біблія за 30 хвилин", "Interview with Elon Musk", "Кулінарний влог: готуємо борщ", "Мотивація для ранкового бігу", "Що подивитися на Netflix цього місяця", "Bible Explained in 30 Minutes"),
  c("Bible Explained in 30 Minutes", "Time Management for Students", "Home Workout No Equipment", "Як скласти ЗНО з математики на 200", "Cooking Vlog: Homemade Lasagna", "Історія Київської Русі за 10 хвилин", "Що подивитися на Netflix цього місяця", "Тренування вдома без обладнання", "Unboxing Weird Tech Gadgets", "The History of Ancient Rome in 10 Minutes"),
  c("Розпаковка AliExpress: смішні покупки", "Top 10 Places to Visit in Europe", "Історія Київської Русі за 10 хвилин", "iPhone 15 Review: Is It Worth It?", "Поради з тайм-менеджменту для студентів", "SAT Math Tips and Tricks", "How to Make a Short Film by Yourself"),
  c("iPhone 15 Review: Is It Worth It?", "Біблія за 30 хвилин", "How to Learn to Code from Scratch", "Vlog: Hiking in the Alps", "Кулінарний влог: готуємо борщ", "Що подивитися на Netflix цього місяця", "Мотивація для ранкового бігу", "Як скласти ЗНО з математики на 200", "ТОП-10 місць для відпочинку в Україні", "Інтерв’ю з Іваном Марчуком"),
  c("The History of Ancient Rome in 10 Minutes", "Біблія за 30 хвилин", "Morning Routine for Productivity", "Як скласти ЗНО з математики на 200", "Поради з тайм-менеджменту для студентів", "How to Learn to Code from Scratch", "Влог з Карпат: піший похід", "What to Watch on Netflix This Month"),
  c("Поради з тайм-менеджменту для студентів", "Як навчитися програмувати з нуля", "Bible Explained in 30 Minutes", "Morning Routine for Productivity", "Unboxing Weird Tech Gadgets", "Мотивація для ранкового бігу", "Як зняти короткометражний фільм самостійно", "What to Watch on Netflix This Month", "iPhone 15 Review: Is It Worth It?", "Cooking Vlog: Homemade Lasagna", "SAT Math Tips and Tricks"),
  c("Як навчитися програмувати з нуля", "Кулінарний влог: готуємо борщ", "SAT Math Tips and Tricks", "Bible Explained in 30 Minutes", "Як зняти короткометражний фільм самостійно", "Що подивитися на Netflix цього місяця", "Interview with Elon Musk", "Vlog: Hiking in the Alps", "Інтерв’ю з Іваном Марчуком"),
  c("Cooking Vlog: Homemade Lasagna", "Як скласти ЗНО з математики на 200", "Time Management for Students", "Як зняти короткометражний фільм самостійно", "Історія Київської Русі за 10 хвилин", "Огляд нового iPhone українською", "What to Watch on Netflix This Month", "Інтерв’ю з Іваном Марчуком", "Мотивація для ранкового бігу"),
  c("iPhone 15 Review: Is It Worth It?", "Як скласти ЗНО з математики на 200", "Влог з Карпат: піший похід", "Top 10 Places to Visit in Europe", "Огляд нового iPhone українською", "Як навчитися програмувати з нуля", "Біблія за 30 хвилин"),
  c("Top 10 Places to Visit in Europe", "Unboxing Weird Tech Gadgets", "What to Watch on Netflix This Month", "The History of Ancient Rome in 10 Minutes", "SAT Math Tips and Tricks", "Мотивація для ранкового бігу"),
  c("Vlog: Hiking in the Alps", "Поради з тайм-менеджменту для студентів", "Bible Explained in 30 Minutes", "What to Watch on Netflix This Month", "Як скласти ЗНО з математики на 200", "The History of Ancient Rome in 10 Minutes", "Розпаковка AliExpress: смішні покупки", "Тренування вдома без обладнання"),
  c("How to Learn to Code from Scratch", "The History of Ancient Rome in 10 Minutes", "Як скласти ЗНО з математики на 200", "Кулінарний влог: готуємо борщ", "Top 10 Places to Visit in Europe", "Що подивитися на Netflix цього місяця", "Як навчитися програмувати з нуля", "Мотивація для ранкового бігу", "Біблія за 30 хвилин"),
  c("How to Learn to Code from Scratch", "Unboxing Weird Tech Gadgets", "SAT Math Tips and Tricks", "Morning Routine for Productivity", "Bible Explained in 30 Minutes", "Як зняти короткометражний фільм самостійно", "iPhone 15 Review: Is It Worth It?", "Огляд нового iPhone українською"),
  c("Кулінарний влог: готуємо борщ", "Як навчитися програмувати з нуля", "Розпаковка AliExpress: смішні покупки", "Unboxing Weird Tech Gadgets", "The History of Ancient Rome in 10 Minutes", "ТОП-10 місць для відпочинку в Україні", "Тренування вдома без обладнання"),
  c("Interview with Elon Musk", "Home Workout No Equipment", "Як зняти короткометражний фільм самостійно", "Огляд нового iPhone українською", "Що подивитися на Netflix цього місяця", "SAT Math Tips and Tricks", "Поради з тайм-менеджменту для студентів", "Влог з Карпат: піший похід", "The History of Ancient Rome in 10 Minutes", "Top 10 Places to Visit in Europe", "Як скласти ЗНО з математики на 200"),
  c("Як скласти ЗНО з математики на 200", "How to Make a Short Film by Yourself", "Розпаковка AliExpress: смішні покупки", "Interview with Elon Musk", "Cooking Vlog: Homemade Lasagna", "Що подивитися на Netflix цього місяця", "Home Workout No Equipment"),
  c("Кулінарний влог: готуємо борщ", "The History of Ancient Rome in 10 Minutes", "Біблія за 30 хвилин", "ТОП-10 місць для відпочинку в Україні", "Як скласти ЗНО з математики на 200", "How to Make a Short Film by Yourself", "Що подивитися на Netflix цього місяця", "Morning Routine for Productivity", "Time Management for Students"),
  c("Time Management for Students", "Як зняти короткометражний фільм самостійно", "Розпаковка AliExpress: смішні покупки", "Що подивитися на Netflix цього місяця", "Кулінарний влог: готуємо борщ", "How to Learn to Code from Scratch"),
  c("Top 10 Places to Visit in Europe", "Біблія за 30 хвилин", "Мотивація для ранкового бігу", "Тренування вдома без обладнання", "Unboxing Weird Tech Gadgets", "Як скласти ЗНО з математики на 200", "Що подивитися на Netflix цього місяця", "Home Workout No Equipment", "Як зняти короткометражний фільм самостійно", "Розпаковка AliExpress: смішні покупки", "Vlog: Hiking in the Alps"),
  c("Інтерв’ю з Іваном Марчуком", "Тренування вдома без обладнання", "Біблія за 30 хвилин", "Як зняти короткометражний фільм самостійно", "What to Watch on Netflix This Month", "Розпаковка AliExpress: смішні покупки", "Огляд нового iPhone українською", "Time Management for Students"),
  c("Біблія за 30 хвилин", "The History of Ancient Rome in 10 Minutes", "Time Management for Students", "Як зняти короткометражний фільм самостійно", "Кулінарний влог: готуємо борщ", "ТОП-10 місць для відпочинку в Україні", "Мотивація для ранкового бігу", "Unboxing Weird Tech Gadgets"),
  c("Як скласти ЗНО з математики на 200", "Unboxing Weird Tech Gadgets", "Top 10 Places to Visit in Europe", "Огляд нового iPhone українською", "Влог з Карпат: піший похід", "How to Learn to Code from Scratch", "Як зняти короткометражний фільм самостійно", "Що подивитися на Netflix цього місяця", "Інтерв’ю з Іваном Марчуком"),
  c("Як навчитися програмувати з нуля", "How to Make a Short Film by Yourself", "Cooking Vlog: Homemade Lasagna", "Розпаковка AliExpress: смішні покупки", "Interview with Elon Musk", "Огляд нового iPhone українською", "Top 10 Places to Visit in Europe"),
  c("Огляд нового iPhone українською", "The History of Ancient Rome in 10 Minutes", "Time Management for Students", "Як навчитися програмувати з нуля", "Top 10 Places to Visit in Europe", "ТОП-10 місць для відпочинку в Україні", "Біблія за 30 хвилин", "Влог з Карпат: піший похід", "Як зняти короткометражний фільм самостійно", "Home Workout No Equipment", "Розпаковка AliExpress: смішні покупки"),
  c("Unboxing Weird Tech Gadgets", "Як скласти ЗНО з математики на 200", "How to Make a Short Film by Yourself", "Як навчитися програмувати з нуля", "The History of Ancient Rome in 10 Minutes", "Morning Routine for Productivity", "SAT Math Tips and Tricks", "Time Management for Students", "Interview with Elon Musk"),
  c("Як навчитися програмувати з нуля", "Мотивація для ранкового бігу", "Cooking Vlog: Homemade Lasagna", "Home Workout No Equipment", "Кулінарний влог: готуємо борщ", "How to Learn to Code from Scratch", "Історія Київської Русі за 10 хвилин"),
  c("The History of Ancient Rome in 10 Minutes", "Тренування вдома без обладнання", "Time Management for Students", "Біблія за 30 хвилин", "Розпаковка AliExpress: смішні покупки", "How to Learn to Code from Scratch", "SAT Math Tips and Tricks", "Інтерв’ю з Іваном Марчуком"),
  c("Інтерв’ю з Іваном Марчуком", "Vlog: Hiking in the Alps", "iPhone 15 Review: Is It Worth It?", "How to Make a Short Film by Yourself", "Кулінарний влог: готуємо борщ", "Як зняти короткометражний фільм самостійно", "SAT Math Tips and Tricks", "Unboxing Weird Tech Gadgets", "Як скласти ЗНО з математики на 200", "What to Watch on Netflix This Month"),
  c("Як навчитися програмувати з нуля", "Cooking Vlog: Homemade Lasagna", "How to Learn to Code from Scratch", "How to Make a Short Film by Yourself", "Розпаковка AliExpress: смішні покупки", "Home Workout No Equipment", "The History of Ancient Rome in 10 Minutes", "Огляд нового iPhone українською", "Інтерв’ю з Іваном Марчуком", "Кулінарний влог: готуємо борщ", "Top 10 Places to Visit in Europe"),
  c("Що подивитися на Netflix цього місяця", "Розпаковка AliExpress: смішні покупки", "Біблія за 30 хвилин", "Top 10 Places to Visit in Europe", "Історія Київської Русі за 10 хвилин", "Як скласти ЗНО з математики на 200", "Як навчитися програмувати з нуля", "Home Workout No Equipment", "Тренування вдома без обладнання", "Як зняти короткометражний фільм самостійно", "Огляд нового iPhone українською"),
  c("Як скласти ЗНО з математики на 200", "Interview with Elon Musk", "Мотивація для ранкового бігу", "Home Workout No Equipment", "Як навчитися програмувати з нуля", "Біблія за 30 хвилин", "What to Watch on Netflix This Month", "Top 10 Places to Visit in Europe", "How to Learn to Code from Scratch", "Що подивитися на Netflix цього місяця"),
  c("How to Make a Short Film by Yourself", "Біблія за 30 хвилин", "Time Management for Students", "Кулінарний влог: готуємо борщ", "Interview with Elon Musk", "Історія Київської Русі за 10 хвилин", "Як навчитися програмувати з нуля", "iPhone 15 Review: Is It Worth It?", "Як зняти короткометражний фільм самостійно"),
  c("The History of Ancient Rome in 10 Minutes", "Як навчитися програмувати з нуля", "How to Learn to Code from Scratch", "Кулінарний влог: готуємо борщ", "Unboxing Weird Tech Gadgets", "Vlog: Hiking in the Alps", "Огляд нового iPhone українською"),
  c("Огляд нового iPhone українською", "What to Watch on Netflix This Month", "Як зняти короткометражний фільм самостійно", "iPhone 15 Review: Is It Worth It?", "How to Learn to Code from Scratch", "Morning Routine for Productivity", "SAT Math Tips and Tricks"),
  c("Home Workout No Equipment", "Cooking Vlog: Homemade Lasagna", "What to Watch on Netflix This Month", "Top 10 Places to Visit in Europe", "Vlog: Hiking in the Alps", "Розпаковка AliExpress: смішні покупки", "Біблія за 30 хвилин", "Історія Київської Русі за 10 хвилин", "Як навчитися програмувати з нуля"),
  c("Як скласти ЗНО з математики на 200", "Кулінарний влог: готуємо борщ", "Time Management for Students", "Історія Київської Русі за 10 хвилин", "How to Learn to Code from Scratch", "What to Watch on Netflix This Month", "Interview with Elon Musk", "Bible Explained in 30 Minutes"),
  c("Влог з Карпат: піший похід", "Що подивитися на Netflix цього місяця", "Home Workout No Equipment", "Як зняти короткометражний фільм самостійно", "Time Management for Students", "Тренування вдома без обладнання"),
  c("Розпаковка AliExpress: смішні покупки", "Історія Київської Русі за 10 хвилин", "Поради з тайм-менеджменту для студентів", "How to Make a Short Film by Yourself", "Time Management for Students", "Bible Explained in 30 Minutes", "Interview with Elon Musk", "ТОП-10 місць для відпочинку в Україні"),
  c("Як скласти ЗНО з математики на 200", "Огляд нового iPhone українською", "Home Workout No Equipment", "Cooking Vlog: Homemade Lasagna", "Біблія за 30 хвилин", "Як навчитися програмувати з нуля", "Інтерв’ю з Іваном Марчуком", "Top 10 Places to Visit in Europe"),
  c("Unboxing Weird Tech Gadgets", "Історія Київської Русі за 10 хвилин", "Interview with Elon Musk", "Як навчитися програмувати з нуля", "Top 10 Places to Visit in Europe", "Як скласти ЗНО з математики на 200", "Bible Explained in 30 Minutes", "How to Learn to Code from Scratch"),
  c("Як навчитися програмувати з нуля", "Morning Routine for Productivity", "Top 10 Places to Visit in Europe", "Огляд нового iPhone українською", "Як зняти короткометражний фільм самостійно", "Біблія за 30 хвилин", "Влог з Карпат: піший похід", "Тренування вдома без обладнання"),
  c("Що подивитися на Netflix цього місяця", "Як зняти короткометражний фільм самостійно", "Home Workout No Equipment", "ТОП-10 місць для відпочинку в Україні", "Top 10 Places to Visit in Europe", "Влог з Карпат: піший похід", "Як скласти ЗНО з математики на 200", "Інтерв’ю з Іваном Марчуком", "How to Learn to Code from Scratch", "iPhone 15 Review: Is It Worth It?", "Біблія за 30 хвилин", "Time Management for Students"),
  c("Як зняти короткометражний фільм самостійно", "Біблія за 30 хвилин", "iPhone 15 Review: Is It Worth It?", "ТОП-10 місць для відпочинку в Україні", "The History of Ancient Rome in 10 Minutes", "Time Management for Students", "Інтерв’ю з Іваном Марчуком", "Кулінарний влог: готуємо борщ", "How to Make a Short Film by Yourself"),
  c("Bible Explained in 30 Minutes", "Interview with Elon Musk", "The History of Ancient Rome in 10 Minutes", "Як навчитися програмувати з нуля", "Мотивація для ранкового бігу", "Влог з Карпат: піший похід", "Cooking Vlog: Homemade Lasagna", "Unboxing Weird Tech Gadgets", "Тренування вдома без обладнання", "SAT Math Tips and Tricks", "Як зняти короткометражний фільм самостійно"),
  c("iPhone 15 Review: Is It Worth It?", "The History of Ancient Rome in 10 Minutes", "Як скласти ЗНО з математики на 200", "Інтерв’ю з Іваном Марчуком", "Кулінарний влог: готуємо борщ", "Home Workout No Equipment", "How to Learn to Code from Scratch"),
  c("ТОП-10 місць для відпочинку в Україні", "How to Learn to Code from Scratch", "SAT Math Tips and Tricks", "Cooking Vlog: Homemade Lasagna", "Як скласти ЗНО з математики на 200", "Interview with Elon Musk", "Vlog: Hiking in the Alps", "Як зняти короткометражний фільм самостійно", "Біблія за 30 хвилин", "Мотивація для ранкового бігу", "Розпаковка AliExpress: смішні покупки", "What to Watch on Netflix This Month"),
  c("Розпаковка AliExpress: смішні покупки", "Як зняти короткометражний фільм самостійно", "How to Make a Short Film by Yourself", "iPhone 15 Review: Is It Worth It?", "How to Learn to Code from Scratch", "Інтерв’ю з Іваном Марчуком", "Історія Київської Русі за 10 хвилин", "Що подивитися на Netflix цього місяця"),
  c("Top 10 Places to Visit in Europe", "Огляд нового iPhone українською", "Кулінарний влог: готуємо борщ", "Як зняти короткометражний фільм самостійно", "Історія Київської Русі за 10 хвилин", "Morning Routine for Productivity"),
  c("Як навчитися програмувати з нуля", "Interview with Elon Musk", "Bible Explained in 30 Minutes", "Cooking Vlog: Homemade Lasagna", "Top 10 Places to Visit in Europe", "Огляд нового iPhone українською", "What to Watch on Netflix This Month", "The History of Ancient Rome in 10 Minutes"),
  c("How to Make a Short Film by Yourself", "Time Management for Students", "The History of Ancient Rome in 10 Minutes", "Огляд нового iPhone українською", "Інтерв’ю з Іваном Марчуком", "Unboxing Weird Tech Gadgets", "Cooking Vlog: Homemade Lasagna", "Vlog: Hiking in the Alps", "Top 10 Places to Visit in Europe", "Мотивація для ранкового бігу"),
  c("Що подивитися на Netflix цього місяця", "Мотивація для ранкового бігу", "Vlog: Hiking in the Alps", "Як скласти ЗНО з математики на 200", "Як зняти короткометражний фільм самостійно", "How to Learn to Code from Scratch", "Кулінарний влог: готуємо борщ", "Поради з тайм-менеджменту для студентів", "Top 10 Places to Visit in Europe", "Біблія за 30 хвилин", "Time Management for Students"),
  c("Інтерв’ю з Іваном Марчуком", "Time Management for Students", "ТОП-10 місць для відпочинку в Україні", "Як скласти ЗНО з математики на 200", "Як зняти короткометражний фільм самостійно", "Тренування вдома без обладнання", "Unboxing Weird Tech Gadgets", "Кулінарний влог: готуємо борщ"),
  c("How to Learn to Code from Scratch", "Top 10 Places to Visit in Europe", "Огляд нового iPhone українською", "iPhone 15 Review: Is It Worth It?", "The History of Ancient Rome in 10 Minutes", "Interview with Elon Musk", "Історія Київської Русі за 10 хвилин", "Home Workout No Equipment"),
  c("Мотивація для ранкового бігу", "The History of Ancient Rome in 10 Minutes", "How to Make a Short Film by Yourself", "Розпаковка AliExpress: смішні покупки", "What to Watch on Netflix This Month", "Біблія за 30 хвилин", "Що подивитися на Netflix цього місяця", "Інтерв’ю з Іваном Марчуком", "iPhone 15 Review: Is It Worth It?", "Vlog: Hiking in the Alps", "Як навчитися програмувати з нуля", "Як скласти ЗНО з математики на 200"),
  c("Біблія за 30 хвилин", "Огляд нового iPhone українською", "Top 10 Places to Visit in Europe", "Поради з тайм-менеджменту для студентів", "How to Make a Short Film by Yourself", "Як скласти ЗНО з математики на 200", "Влог з Карпат: піший похід", "Кулінарний влог: готуємо борщ"),
  c("Як навчитися програмувати з нуля", "Біблія за 30 хвилин", "Morning Routine for Productivity", "SAT Math Tips and Tricks", "Кулінарний влог: готуємо борщ", "The History of Ancient Rome in 10 Minutes", "Як скласти ЗНО з математики на 200", "Home Workout No Equipment"),
  c("Як навчитися програмувати з нуля", "Time Management for Students", "How to Make a Short Film by Yourself", "Vlog: Hiking in the Alps", "Тренування вдома без обладнання", "Поради з тайм-менеджменту для студентів"),
  c("Біблія за 30 хвилин", "Як скласти ЗНО з математики на 200", "Interview with Elon Musk", "Як зняти короткометражний фільм самостійно", "Що подивитися на Netflix цього місяця", "Історія Київської Русі за 10 хвилин", "Кулінарний влог: готуємо борщ", "Тренування вдома без обладнання", "Bible Explained in 30 Minutes"),
  c("Time Management for Students", "The History of Ancient Rome in 10 Minutes", "SAT Math Tips and Tricks", "Як скласти ЗНО з математики на 200", "Огляд нового iPhone українською", "Cooking Vlog: Homemade Lasagna", "Кулінарний влог: готуємо борщ", "Влог з Карпат: піший похід", "Тренування вдома без обладнання", "ТОП-10 місць для відпочинку в Україні"),
  c("Як скласти ЗНО з математики на 200", "Поради з тайм-менеджменту для студентів", "Vlog: Hiking in the Alps", "Як навчитися програмувати з нуля", "ТОП-10 місць для відпочинку в Україні", "Cooking Vlog: Homemade Lasagna", "How to Make a Short Film by Yourself", "Огляд нового iPhone українською", "Біблія за 30 хвилин"),
  c("Як скласти ЗНО з математики на 200", "Кулінарний влог: готуємо борщ", "How to Learn to Code from Scratch", "Огляд нового iPhone українською", "SAT Math Tips and Tricks", "Влог з Карпат: піший похід", "Time Management for Students", "How to Make a Short Film by Yourself"),
  c("Top 10 Places to Visit in Europe", "The History of Ancient Rome in 10 Minutes", "iPhone 15 Review: Is It Worth It?", "Розпаковка AliExpress: смішні покупки", "Time Management for Students", "How to Learn to Code from Scratch", "Кулінарний влог: готуємо борщ", "Інтерв’ю з Іваном Марчуком", "Unboxing Weird Tech Gadgets"),
  c("How to Make a Short Film by Yourself", "Morning Routine for Productivity", "Кулінарний влог: готуємо борщ", "ТОП-10 місць для відпочинку в Україні", "Interview with Elon Musk", "iPhone 15 Review: Is It Worth It?", "Огляд нового iPhone українською", "Top 10 Places to Visit in Europe", "Як скласти ЗНО з математики на 200"),
  c("Unboxing Weird Tech Gadgets", "Як зняти короткометражний фільм самостійно", "Bible Explained in 30 Minutes", "Home Workout No Equipment", "Історія Київської Русі за 10 хвилин", "How to Learn to Code from Scratch", "Interview with Elon Musk", "Як навчитися програмувати з нуля"),
  c("Історія Київської Русі за 10 хвилин", "What to Watch on Netflix This Month", "The History of Ancient Rome in 10 Minutes", "Як зняти короткометражний фільм самостійно", "Interview with Elon Musk", "Morning Routine for Productivity", "SAT Math Tips and Tricks", "Time Management for Students", "How to Make a Short Film by Yourself", "Огляд нового iPhone українською"),
  c("Мотивація для ранкового бігу", "Інтерв’ю з Іваном Марчуком", "Як скласти ЗНО з математики на 200", "Кулінарний влог: готуємо борщ", "Огляд нового iPhone українською", "Vlog: Hiking in the Alps", "How to Make a Short Film by Yourself", "Що подивитися на Netflix цього місяця", "How to Learn to Code from Scratch"),
  c("Огляд нового iPhone українською", "Як скласти ЗНО з математики на 200", "What to Watch on Netflix This Month", "Morning Routine for Productivity", "How to Learn to Code from Scratch", "Розпаковка AliExpress: смішні покупки"),
  c("Що подивитися на Netflix цього місяця", "Vlog: Hiking in the Alps", "Інтерв’ю з Іваном Марчуком", "Як навчитися програмувати з нуля", "The History of Ancient Rome in 10 Minutes", "Top 10 Places to Visit in Europe", "Morning Routine for Productivity", "How to Learn to Code from Scratch"),
  c("Як навчитися програмувати з нуля", "Кулінарний влог: готуємо борщ", "Top 10 Places to Visit in Europe", "Unboxing Weird Tech Gadgets", "Bible Explained in 30 Minutes", "Тренування вдома без обладнання", "How to Learn to Code from Scratch", "Interview with Elon Musk", "Історія Київської Русі за 10 хвилин", "The History of Ancient Rome in 10 Minutes", "Як зняти короткометражний фільм самостійно"),
  c("Кулінарний влог: готуємо борщ", "Як зняти короткометражний фільм самостійно", "Інтерв’ю з Іваном Марчуком", "Як скласти ЗНО з математики на 200", "Біблія за 30 хвилин", "SAT Math Tips and Tricks", "Cooking Vlog: Homemade Lasagna", "What to Watch on Netflix This Month", "Влог з Карпат: піший похід"),
  c("The History of Ancient Rome in 10 Minutes", "Morning Routine for Productivity", "Top 10 Places to Visit in Europe", "Vlog: Hiking in the Alps", "Bible Explained in 30 Minutes", "iPhone 15 Review: Is It Worth It?", "Поради з тайм-менеджменту для студентів"),
  c("Як зняти короткометражний фільм самостійно", "Що подивитися на Netflix цього місяця", "Bible Explained in 30 Minutes", "Cooking Vlog: Homemade Lasagna", "Тренування вдома без обладнання", "How to Learn to Code from Scratch", "Unboxing Weird Tech Gadgets"),
  c("Interview with Elon Musk", "Біблія за 30 хвилин", "Історія Київської Русі за 10 хвилин", "Кулінарний влог: готуємо борщ", "Time Management for Students", "What to Watch on Netflix This Month", "Розпаковка AliExpress: смішні покупки", "Як зняти короткометражний фільм самостійно", "Home Workout No Equipment", "Cooking Vlog: Homemade Lasagna"),
  c("Історія Київської Русі за 10 хвилин", "Як навчитися програмувати з нуля", "Як скласти ЗНО з математики на 200", "Cooking Vlog: Homemade Lasagna", "Unboxing Weird Tech Gadgets", "Розпаковка AliExpress: смішні покупки", "Влог з Карпат: піший похід", "SAT Math Tips and Tricks", "Тренування вдома без обладнання"),
  c("Bible Explained in 30 Minutes", "Top 10 Places to Visit in Europe", "Тренування вдома без обладнання", "Кулінарний влог: готуємо борщ", "The History of Ancient Rome in 10 Minutes", "Morning Routine for Productivity", "Розпаковка AliExpress: смішні покупки", "How to Learn to Code from Scratch", "Огляд нового iPhone українською"),
  c("Top 10 Places to Visit in Europe", "Поради з тайм-менеджменту для студентів", "SAT Math Tips and Tricks", "Біблія за 30 хвилин", "Як скласти ЗНО з математики на 200", "Unboxing Weird Tech Gadgets", "What to Watch on Netflix This Month"),
  c("Як навчитися програмувати з нуля", "Interview with Elon Musk", "Unboxing Weird Tech Gadgets", "Як скласти ЗНО з математики на 200", "The History of Ancient Rome in 10 Minutes", "What to Watch on Netflix This Month", "iPhone 15 Review: Is It Worth It?"),
  c("SAT Math Tips and Tricks", "Cooking Vlog: Homemade Lasagna", "ТОП-10 місць для відпочинку в Україні", "Поради з тайм-менеджменту для студентів", "Що подивитися на Netflix цього місяця", "Тренування вдома без обладнання", "Home Workout No Equipment", "Top 10 Places to Visit in Europe", "Розпаковка AliExpress: смішні покупки", "Влог з Карпат: піший похід"),
  c("Кулінарний влог: готуємо борщ", "Interview with Elon Musk", "How to Make a Short Film by Yourself", "Огляд нового iPhone українською", "Як навчитися програмувати з нуля", "Що подивитися на Netflix цього місяця", "Bible Explained in 30 Minutes", "The History of Ancient Rome in 10 Minutes"),
  c("Історія Київської Русі за 10 хвилин", "Як зняти короткометражний фільм самостійно", "Top 10 Places to Visit in Europe", "The History of Ancient Rome in 10 Minutes", "Bible Explained in 30 Minutes", "Morning Routine for Productivity", "Як скласти ЗНО з математики на 200"),
  c("Time Management for Students", "What to Watch on Netflix This Month", "Як навчитися програмувати з нуля", "The History of Ancient Rome in 10 Minutes", "Інтерв’ю з Іваном Марчуком", "How to Make a Short Film by Yourself", "Morning Routine for Productivity", "Мотивація для ранкового бігу", "Влог з Карпат: піший похід", "Як скласти ЗНО з математики на 200", "Bible Explained in 30 Minutes", "Тренування вдома без обладнання"),
  c("Поради з тайм-менеджменту для студентів", "Кулінарний влог: готуємо борщ", "Як скласти ЗНО з математики на 200", "Розпаковка AliExpress: смішні покупки", "What to Watch on Netflix This Month", "Bible Explained in 30 Minutes", "iPhone 15 Review: Is It Worth It?", "Як зняти короткометражний фільм самостійно", "ТОП-10 місць для відпочинку в Україні", "Morning Routine for Productivity"),
  c("Як зняти короткометражний фільм самостійно", "How to Learn to Code from Scratch", "Time Management for Students", "Interview with Elon Musk", "Кулінарний влог: готуємо борщ", "Top 10 Places to Visit in Europe", "Unboxing Weird Tech Gadgets", "Історія Київської Русі за 10 хвилин", "Розпаковка AliExpress: смішні покупки", "Як навчитися програмувати з нуля", "Що подивитися на Netflix цього місяця"),
  c("Як навчитися програмувати з нуля", "The History of Ancient Rome in 10 Minutes", "Time Management for Students", "iPhone 15 Review: Is It Worth It?", "How to Learn to Code from Scratch", "Влог з Карпат: піший похід", "Тренування вдома без обладнання", "Як зняти короткометражний фільм самостійно", "Кулінарний влог: готуємо борщ", "Bible Explained in 30 Minutes"),
  c("How to Learn to Code from Scratch", "Interview with Elon Musk", "Поради з тайм-менеджменту для студентів", "Як скласти ЗНО з математики на 200", "Bible Explained in 30 Minutes", "Кулінарний влог: готуємо борщ", "Top 10 Places to Visit in Europe", "Влог з Карпат: піший похід", "Мотивація для ранкового бігу"),
  c("Що подивитися на Netflix цього місяця", "Історія Київської Русі за 10 хвилин", "Home Workout No Equipment", "Кулінарний влог: готуємо борщ", "iPhone 15 Review: Is It Worth It?", "Time Management for Students", "How to Learn to Code from Scratch", "Мотивація для ранкового бігу", "Як навчитися програмувати з нуля", "Як зняти короткометражний фільм самостійно", "Огляд нового iPhone українською"),
  c("Як зняти короткометражний фільм самостійно", "What to Watch on Netflix This Month", "Top 10 Places to Visit in Europe", "Як скласти ЗНО з математики на 200", "Інтерв’ю з Іваном Марчуком", "Біблія за 30 хвилин", "Тренування вдома без обладнання"),
  c("How to Make a Short Film by Yourself", "Кулінарний влог: готуємо борщ", "Що подивитися на Netflix цього місяця", "Біблія за 30 хвилин", "SAT Math Tips and Tricks", "Як навчитися програмувати з нуля", "Unboxing Weird Tech Gadgets", "Bible Explained in 30 Minutes", "Top 10 Places to Visit in Europe"),
  c("SAT Math Tips and Tricks", "Інтерв’ю з Іваном Марчуком", "Огляд нового iPhone українською", "Біблія за 30 хвилин", "Bible Explained in 30 Minutes", "Влог з Карпат: піший похід", "Top 10 Places to Visit in Europe", "Мотивація для ранкового бігу", "Кулінарний влог: готуємо борщ", "How to Learn to Code from Scratch"),
  c("Як зняти короткометражний фільм самостійно", "What to Watch on Netflix This Month", "Огляд нового iPhone українською", "Top 10 Places to Visit in Europe", "iPhone 15 Review: Is It Worth It?", "Interview with Elon Musk", "Мотивація для ранкового бігу"),
  c("Home Workout No Equipment", "Top 10 Places to Visit in Europe", "Interview with Elon Musk", "How to Make a Short Film by Yourself", "Мотивація для ранкового бігу", "Як скласти ЗНО з математики на 200", "Як навчитися програмувати з нуля", "iPhone 15 Review: Is It Worth It?"),
  c("Інтерв’ю з Іваном Марчуком", "Як зняти короткометражний фільм самостійно", "How to Learn to Code from Scratch", "Vlog: Hiking in the Alps", "Кулінарний влог: готуємо борщ", "Як скласти ЗНО з математики на 200", "Bible Explained in 30 Minutes", "Morning Routine for Productivity"),
  c("Time Management for Students", "Interview with Elon Musk", "Home Workout No Equipment", "Як скласти ЗНО з математики на 200", "Кулінарний влог: готуємо борщ", "Біблія за 30 хвилин", "Влог з Карпат: піший похід", "Мотивація для ранкового бігу", "Як навчитися програмувати з нуля", "Огляд нового iPhone українською"),
  c("Кулінарний влог: готуємо борщ", "Як скласти ЗНО з математики на 200", "What to Watch on Netflix This Month", "Поради з тайм-менеджменту для студентів", "Інтерв’ю з Іваном Марчуком", "iPhone 15 Review: Is It Worth It?", "Огляд нового iPhone українською", "ТОП-10 місць для відпочинку в Україні", "Top 10 Places to Visit in Europe", "Розпаковка AliExpress: смішні покупки"),
  c("Що подивитися на Netflix цього місяця", "SAT Math Tips and Tricks", "How to Learn to Code from Scratch", "The History of Ancient Rome in 10 Minutes", "Розпаковка AliExpress: смішні покупки", "Cooking Vlog: Homemade Lasagna", "Home Workout No Equipment", "Vlog: Hiking in the Alps", "Time Management for Students", "Як навчитися програмувати з нуля"),
  c("How to Learn to Code from Scratch", "Як навчитися програмувати з нуля", "Cooking Vlog: Homemade Lasagna", "Interview with Elon Musk", "The History of Ancient Rome in 10 Minutes", "Біблія за 30 хвилин", "Time Management for Students", "What to Watch on Netflix This Month", "Мотивація для ранкового бігу", "ТОП-10 місць для відпочинку в Україні", "Влог з Карпат: піший похід"),
  c("How to Learn to Code from Scratch", "The History of Ancient Rome in 10 Minutes", "Інтерв’ю з Іваном Марчуком", "Розпаковка AliExpress: смішні покупки", "Що подивитися на Netflix цього місяця", "Vlog: Hiking in the Alps", "Як скласти ЗНО з математики на 200", "Time Management for Students", "Як зняти короткометражний фільм самостійно", "Кулінарний влог: готуємо борщ"),
  c("Поради з тайм-менеджменту для студентів", "What to Watch on Netflix This Month", "How to Make a Short Film by Yourself", "Interview with Elon Musk", "Як навчитися програмувати з нуля", "iPhone 15 Review: Is It Worth It?", "Cooking Vlog: Homemade Lasagna", "Мотивація для ранкового бігу"),
  c("Як зняти короткометражний фільм самостійно", "Як навчитися програмувати з нуля", "Біблія за 30 хвилин", "Interview with Elon Musk", "Cooking Vlog: Homemade Lasagna", "ТОП-10 місць для відпочинку в Україні", "What to Watch on Netflix This Month", "The History of Ancient Rome in 10 Minutes", "Top 10 Places to Visit in Europe"),
  c("Home Workout No Equipment", "How to Make a Short Film by Yourself", "How to Learn to Code from Scratch", "Time Management for Students", "Кулінарний влог: готуємо борщ", "Мотивація для ранкового бігу", "Влог з Карпат: піший похід", "Як навчитися програмувати з нуля"),
  c("Unboxing Weird Tech Gadgets", "Time Management for Students", "How to Learn to Code from Scratch", "Як скласти ЗНО з математики на 200", "Top 10 Places to Visit in Europe", "iPhone 15 Review: Is It Worth It?", "Що подивитися на Netflix цього місяця", "Home Workout No Equipment"),
  c("ТОП-10 місць для відпочинку в Україні", "The History of Ancient Rome in 10 Minutes", "Як зняти короткометражний фільм самостійно", "How to Learn to Code from Scratch", "iPhone 15 Review: Is It Worth It?", "What to Watch on Netflix This Month", "Як навчитися програмувати з нуля", "Біблія за 30 хвилин", "Мотивація для ранкового бігу", "Vlog: Hiking in the Alps", "Тренування вдома без обладнання"),
  c("Time Management for Students", "Як зняти короткометражний фільм самостійно", "Як навчитися програмувати з нуля", "Мотивація для ранкового бігу", "What to Watch on Netflix This Month", "The History of Ancient Rome in 10 Minutes", "Interview with Elon Musk", "Біблія за 30 хвилин", "Розпаковка AliExpress: смішні покупки", "Тренування вдома без обладнання"),
  c("Що подивитися на Netflix цього місяця", "Як скласти ЗНО з математики на 200", "Home Workout No Equipment", "How to Make a Short Film by Yourself", "Як зняти короткометражний фільм самостійно", "Time Management for Students", "Розпаковка AliExpress: смішні покупки", "Історія Київської Русі за 10 хвилин", "Top 10 Places to Visit in Europe"),
  c("The History of Ancient Rome in 10 Minutes", "Top 10 Places to Visit in Europe", "Як зняти короткометражний фільм самостійно", "Як навчитися програмувати з нуля", "Unboxing Weird Tech Gadgets", "Vlog: Hiking in the Alps", "Interview with Elon Musk", "Кулінарний влог: готуємо борщ", "Як скласти ЗНО з математики на 200", "Time Management for Students", "Біблія за 30 хвилин", "iPhone 15 Review: Is It Worth It?"),
  c("Влог з Карпат: піший похід", "Як навчитися програмувати з нуля", "Що подивитися на Netflix цього місяця", "The History of Ancient Rome in 10 Minutes", "Home Workout No Equipment", "Unboxing Weird Tech Gadgets", "Як скласти ЗНО з математики на 200", "Розпаковка AliExpress: смішні покупки", "iPhone 15 Review: Is It Worth It?"),
  c("Огляд нового iPhone українською", "Мотивація для ранкового бігу", "Що подивитися на Netflix цього місяця", "How to Learn to Code from Scratch", "Time Management for Students", "Як зняти короткометражний фільм самостійно", "SAT Math Tips and Tricks", "iPhone 15 Review: Is It Worth It?"),
  c("Поради з тайм-менеджменту для студентів", "Cooking Vlog: Homemade Lasagna", "Що подивитися на Netflix цього місяця", "How to Make a Short Film by Yourself", "Історія Київської Русі за 10 хвилин", "Top 10 Places to Visit in Europe", "Unboxing Weird Tech Gadgets", "Home Workout No Equipment", "Як зняти короткометражний фільм самостійно", "Як скласти ЗНО з математики на 200"),
  c("The History of Ancient Rome in 10 Minutes", "Home Workout No Equipment", "Як навчитися програмувати з нуля", "Unboxing Weird Tech Gadgets", "Кулінарний влог: готуємо борщ", "Time Management for Students", "Cooking Vlog: Homemade Lasagna", "Поради з тайм-менеджменту для студентів", "SAT Math Tips and Tricks"),
  c("The History of Ancient Rome in 10 Minutes", "SAT Math Tips and Tricks", "Що подивитися на Netflix цього місяця", "Bible Explained in 30 Minutes", "Влог з Карпат: піший похід", "How to Learn to Code from Scratch", "ТОП-10 місць для відпочинку в Україні", "Інтерв’ю з Іваном Марчуком", "Як навчитися програмувати з нуля"),
  c("Time Management for Students", "iPhone 15 Review: Is It Worth It?", "Bible Explained in 30 Minutes", "Кулінарний влог: готуємо борщ", "Інтерв’ю з Іваном Марчуком", "How to Make a Short Film by Yourself", "Як зняти короткометражний фільм самостійно", "Огляд нового iPhone українською", "Home Workout No Equipment"),
  c("Біблія за 30 хвилин", "Тренування вдома без обладнання", "Cooking Vlog: Homemade Lasagna", "Vlog: Hiking in the Alps", "Кулінарний влог: готуємо борщ", "SAT Math Tips and Tricks", "Top 10 Places to Visit in Europe"),
  c("Розпаковка AliExpress: смішні покупки", "How to Learn to Code from Scratch", "Interview with Elon Musk", "Home Workout No Equipment", "Як навчитися програмувати з нуля", "Поради з тайм-менеджменту для студентів", "Інтерв’ю з Іваном Марчуком"),
  c("Time Management for Students", "Як скласти ЗНО з математики на 200", "Що подивитися на Netflix цього місяця", "Unboxing Weird Tech Gadgets", "Як навчитися програмувати з нуля", "Інтерв’ю з Іваном Марчуком", "The History of Ancient Rome in 10 Minutes", "Як зняти короткометражний фільм самостійно"),
  c("Як зняти короткометражний фільм самостійно", "What to Watch on Netflix This Month", "Інтерв’ю з Іваном Марчуком", "Home Workout No Equipment", "How to Make a Short Film by Yourself", "iPhone 15 Review: Is It Worth It?", "How to Learn to Code from Scratch", "Time Management for Students", "Тренування вдома без обладнання"),
  c("How to Learn to Code from Scratch", "Як скласти ЗНО з математики на 200", "Bible Explained in 30 Minutes", "Unboxing Weird Tech Gadgets", "Що подивитися на Netflix цього місяця", "Історія Київської Русі за 10 хвилин", "The History of Ancient Rome in 10 Minutes", "Time Management for Students", "Як навчитися програмувати з нуля"),
  c("Top 10 Places to Visit in Europe", "How to Learn to Code from Scratch", "Як навчитися програмувати з нуля", "Як скласти ЗНО з математики на 200", "How to Make a Short Film by Yourself", "Кулінарний влог: готуємо борщ", "Interview with Elon Musk", "Time Management for Students", "Vlog: Hiking in the Alps", "Розпаковка AliExpress: смішні покупки"),
  c("Як зняти короткометражний фільм самостійно", "Кулінарний влог: готуємо борщ", "What to Watch on Netflix This Month", "Як навчитися програмувати з нуля", "The History of Ancient Rome in 10 Minutes", "iPhone 15 Review: Is It Worth It?", "Home Workout No Equipment", "Біблія за 30 хвилин", "Bible Explained in 30 Minutes", "Unboxing Weird Tech Gadgets", "Розпаковка AliExpress: смішні покупки"),
  c("Влог з Карпат: піший похід", "Як зняти короткометражний фільм самостійно", "Top 10 Places to Visit in Europe", "Cooking Vlog: Homemade Lasagna", "Bible Explained in 30 Minutes", "ТОП-10 місць для відпочинку в Україні", "iPhone 15 Review: Is It Worth It?", "The History of Ancient Rome in 10 Minutes"),
  c("ТОП-10 місць для відпочинку в Україні", "Влог з Карпат: піший похід", "Interview with Elon Musk", "What to Watch on Netflix This Month", "Як навчитися програмувати з нуля", "Огляд нового iPhone українською", "SAT Math Tips and Tricks", "Як зняти короткометражний фільм самостійно", "Unboxing Weird Tech Gadgets", "How to Make a Short Film by Yourself"),
  c("Як навчитися програмувати з нуля", "Interview with Elon Musk", "The History of Ancient Rome in 10 Minutes", "Біблія за 30 хвилин", "Top 10 Places to Visit in Europe", "Розпаковка AliExpress: смішні покупки", "Home Workout No Equipment", "Кулінарний влог: готуємо борщ"),
  c("Огляд нового iPhone українською", "SAT Math Tips and Tricks", "Як зняти короткометражний фільм самостійно", "Як навчитися програмувати з нуля", "Біблія за 30 хвилин", "How to Make a Short Film by Yourself", "ТОП-10 місць для відпочинку в Україні", "The History of Ancient Rome in 10 Minutes", "Кулінарний влог: готуємо борщ", "Влог з Карпат: піший похід"),
  c("How to Learn to Code from Scratch", "Поради з тайм-менеджменту для студентів", "Як навчитися програмувати з нуля", "Влог з Карпат: піший похід", "Morning Routine for Productivity", "Top 10 Places to Visit in Europe", "Кулінарний влог: готуємо борщ", "Bible Explained in 30 Minutes", "Історія Київської Русі за 10 хвилин"),
  c("Як навчитися програмувати з нуля", "Top 10 Places to Visit in Europe", "Як зняти короткометражний фільм самостійно", "Bible Explained in 30 Minutes", "Cooking Vlog: Homemade Lasagna", "Тренування вдома без обладнання", "Vlog: Hiking in the Alps", "Що подивитися на Netflix цього місяця", "The History of Ancient Rome in 10 Minutes", "How to Make a Short Film by Yourself", "Історія Київської Русі за 10 хвилин", "Розпаковка AliExpress: смішні покупки"),
  c("Біблія за 30 хвилин", "Interview with Elon Musk", "Як зняти короткометражний фільм самостійно", "SAT Math Tips and Tricks", "Unboxing Weird Tech Gadgets", "Мотивація для ранкового бігу", "ТОП-10 місць для відпочинку в Україні", "Cooking Vlog: Homemade Lasagna", "Розпаковка AliExpress: смішні покупки"),
  c("Історія Київської Русі за 10 хвилин", "Unboxing Weird Tech Gadgets", "Що подивитися на Netflix цього місяця", "Як скласти ЗНО з математики на 200", "Top 10 Places to Visit in Europe", "Біблія за 30 хвилин", "How to Make a Short Film by Yourself", "Як навчитися програмувати з нуля"),
  c("Розпаковка AliExpress: смішні покупки", "Top 10 Places to Visit in Europe", "Unboxing Weird Tech Gadgets", "Morning Routine for Productivity", "Як зняти короткометражний фільм самостійно", "Як навчитися програмувати з нуля", "Interview with Elon Musk", "Біблія за 30 хвилин", "What to Watch on Netflix This Month", "iPhone 15 Review: Is It Worth It?"),
  c("What to Watch on Netflix This Month", "Інтерв’ю з Іваном Марчуком", "Cooking Vlog: Homemade Lasagna", "The History of Ancient Rome in 10 Minutes", "iPhone 15 Review: Is It Worth It?", "How to Make a Short Film by Yourself", "SAT Math Tips and Tricks", "Як зняти короткометражний фільм самостійно"),
  c("iPhone 15 Review: Is It Worth It?", "Bible Explained in 30 Minutes", "Як зняти короткометражний фільм самостійно", "The History of Ancient Rome in 10 Minutes", "Огляд нового iPhone українською", "Home Workout No Equipment", "Morning Routine for Productivity", "Поради з тайм-менеджменту для студентів", "Як навчитися програмувати з нуля", "SAT Math Tips and Tricks", "How to Learn to Code from Scratch"),
  c("Home Workout No Equipment", "Як скласти ЗНО з математики на 200", "How to Learn to Code from Scratch", "Що подивитися на Netflix цього місяця", "Огляд нового iPhone українською", "Біблія за 30 хвилин", "Bible Explained in 30 Minutes"),
  c("Як зняти короткометражний фільм самостійно", "Інтерв’ю з Іваном Марчуком", "Як навчитися програмувати з нуля", "Кулінарний влог: готуємо борщ", "ТОП-10 місць для відпочинку в Україні", "How to Learn to Code from Scratch", "Time Management for Students", "Unboxing Weird Tech Gadgets"),
  c("What to Watch on Netflix This Month", "Огляд нового iPhone українською", "Top 10 Places to Visit in Europe", "Unboxing Weird Tech Gadgets", "Як навчитися програмувати з нуля", "Як зняти короткометражний фільм самостійно", "Time Management for Students", "Home Workout No Equipment", "Vlog: Hiking in the Alps", "Біблія за 30 хвилин", "Тренування вдома без обладнання", "Як скласти ЗНО з математики на 200"),
  c("How to Learn to Code from Scratch", "Тренування вдома без обладнання", "The History of Ancient Rome in 10 Minutes", "Як зняти короткометражний фільм самостійно", "Morning Routine for Productivity", "Bible Explained in 30 Minutes", "What to Watch on Netflix This Month", "Кулінарний влог: готуємо борщ"),
  c("Cooking Vlog: Homemade Lasagna", "Top 10 Places to Visit in Europe", "What to Watch on Netflix This Month", "Як зняти короткометражний фільм самостійно", "Time Management for Students", "Мотивація для ранкового бігу"),
  c("Мотивація для ранкового бігу", "Біблія за 30 хвилин", "Історія Київської Русі за 10 хвилин", "Як зняти короткометражний фільм самостійно", "Як навчитися програмувати з нуля", "Top 10 Places to Visit in Europe", "Home Workout No Equipment"),
  c("Time Management for Students", "Мотивація для ранкового бігу", "Interview with Elon Musk", "Огляд нового iPhone українською", "Як навчитися програмувати з нуля", "Розпаковка AliExpress: смішні покупки", "Кулінарний влог: готуємо борщ", "How to Make a Short Film by Yourself"),
  c("Top 10 Places to Visit in Europe", "Огляд нового iPhone українською", "What to Watch on Netflix This Month", "SAT Math Tips and Tricks", "Time Management for Students", "Home Workout No Equipment", "Як навчитися програмувати з нуля", "Як зняти короткометражний фільм самостійно"),
  c("Як навчитися програмувати з нуля", "Bible Explained in 30 Minutes", "iPhone 15 Review: Is It Worth It?", "Поради з тайм-менеджменту для студентів", "The History of Ancient Rome in 10 Minutes", "Кулінарний влог: готуємо борщ", "Top 10 Places to Visit in Europe", "Morning Routine for Productivity", "Як зняти короткометражний фільм самостійно"),
  c("Home Workout No Equipment", "Історія Київської Русі за 10 хвилин", "The History of Ancient Rome in 10 Minutes", "Кулінарний влог: готуємо борщ", "Unboxing Weird Tech Gadgets", "iPhone 15 Review: Is It Worth It?", "Розпаковка AliExpress: смішні покупки", "Як зняти короткометражний фільм самостійно", "Bible Explained in 30 Minutes", "Що подивитися на Netflix цього місяця"),
  c("Як навчитися програмувати з нуля", "How to Make a Short Film by Yourself", "Біблія за 30 хвилин", "Тренування вдома без обладнання", "Cooking Vlog: Homemade Lasagna", "The History of Ancient Rome in 10 Minutes", "Огляд нового iPhone українською", "Time Management for Students", "Що подивитися на Netflix цього місяця"),
  c("Top 10 Places to Visit in Europe", "Як зняти короткометражний фільм самостійно", "How to Learn to Code from Scratch", "SAT Math Tips and Tricks", "Як скласти ЗНО з математики на 200", "iPhone 15 Review: Is It Worth It?", "Home Workout No Equipment"),
  c("Кулінарний влог: готуємо борщ", "Що подивитися на Netflix цього місяця", "The History of Ancient Rome in 10 Minutes", "Time Management for Students", "Як скласти ЗНО з математики на 200", "Top 10 Places to Visit in Europe", "Як зняти короткометражний фільм самостійно", "How to Learn to Code from Scratch"),
  c("Історія Київської Русі за 10 хвилин", "Розпаковка AliExpress: смішні покупки", "The History of Ancient Rome in 10 Minutes", "SAT Math Tips and Tricks", "Влог з Карпат: піший похід", "Як скласти ЗНО з математики на 200", "What to Watch on Netflix This Month", "Кулінарний влог: готуємо борщ", "Як навчитися програмувати з нуля"),
  c("Interview with Elon Musk", "Що подивитися на Netflix цього місяця", "How to Learn to Code from Scratch", "Як скласти ЗНО з математики на 200", "iPhone 15 Review: Is It Worth It?", "Кулінарний влог: готуємо борщ", "Тренування вдома без обладнання"),
  c("Біблія за 30 хвилин", "Bible Explained in 30 Minutes", "iPhone 15 Review: Is It Worth It?", "Як зняти короткометражний фільм самостійно", "The History of Ancient Rome in 10 Minutes", "Top 10 Places to Visit in Europe", "Як навчитися програмувати з нуля", "Розпаковка AliExpress: смішні покупки"),
  c("Що подивитися на Netflix цього місяця", "Розпаковка AliExpress: смішні покупки", "Cooking Vlog: Homemade Lasagna", "Як навчитися програмувати з нуля", "Time Management for Students", "The History of Ancient Rome in 10 Minutes", "Як зняти короткометражний фільм самостійно", "Біблія за 30 хвилин", "SAT Math Tips and Tricks"),
  c("Що подивитися на Netflix цього місяця", "The History of Ancient Rome in 10 Minutes", "Як навчитися програмувати з нуля", "Інтерв’ю з Іваном Марчуком", "Мотивація для ранкового бігу", "Біблія за 30 хвилин", "Home Workout No Equipment", "Cooking Vlog: Homemade Lasagna"),
  c("Interview with Elon Musk", "Біблія за 30 хвилин", "Як зняти короткометражний фільм самостійно", "Розпаковка AliExpress: смішні покупки", "The History of Ancient Rome in 10 Minutes", "Time Management for Students", "iPhone 15 Review: Is It Worth It?"),
  c("The History of Ancient Rome in 10 Minutes", "Розпаковка AliExpress: смішні покупки", "Влог з Карпат: піший похід", "iPhone 15 Review: Is It Worth It?", "Home Workout No Equipment", "Як навчитися програмувати з нуля", "Time Management for Students", "What to Watch on Netflix This Month", "SAT Math Tips and Tricks", "How to Make a Short Film by Yourself"),
  c("What to Watch on Netflix This Month", "Як зняти короткометражний фільм самостійно", "Біблія за 30 хвилин", "How to Learn to Code from Scratch", "Cooking Vlog: Homemade Lasagna", "Morning Routine for Productivity", "Interview with Elon Musk", "Огляд нового iPhone українською", "Як скласти ЗНО з математики на 200", "Історія Київської Русі за 10 хвилин", "Unboxing Weird Tech Gadgets"),
  c("What to Watch on Netflix This Month", "Біблія за 30 хвилин", "Home Workout No Equipment", "Як зняти короткометражний фільм самостійно", "Cooking Vlog: Homemade Lasagna", "Як скласти ЗНО з математики на 200", "Розпаковка AliExpress: смішні покупки", "Vlog: Hiking in the Alps", "Поради з тайм-менеджменту для студентів", "Інтерв’ю з Іваном Марчуком"),
  c("Як скласти ЗНО з математики на 200", "Влог з Карпат: піший похід", "Cooking Vlog: Homemade Lasagna", "Біблія за 30 хвилин", "What to Watch on Netflix This Month", "Тренування вдома без обладнання", "Як навчитися програмувати з нуля", "SAT Math Tips and Tricks", "Home Workout No Equipment"),
  c("Як зняти короткометражний фільм самостійно", "Огляд нового iPhone українською", "Що подивитися на Netflix цього місяця", "Interview with Elon Musk", "Як скласти ЗНО з математики на 200", "How to Make a Short Film by Yourself", "Кулінарний влог: готуємо борщ", "How to Learn to Code from Scratch", "Time Management for Students", "ТОП-10 місць для відпочинку в Україні"),
  c("Влог з Карпат: піший похід", "ТОП-10 місць для відпочинку в Україні", "Інтерв’ю з Іваном Марчуком", "Огляд нового iPhone українською", "Що подивитися на Netflix цього місяця", "The History of Ancient Rome in 10 Minutes", "Кулінарний влог: готуємо борщ", "Bible Explained in 30 Minutes"),
  c("iPhone 15 Review: Is It Worth It?", "How to Learn to Code from Scratch", "Як скласти ЗНО з математики на 200", "Time Management for Students", "Кулінарний влог: готуємо борщ", "Як зняти короткометражний фільм самостійно", "The History of Ancient Rome in 10 Minutes", "Що подивитися на Netflix цього місяця"),
  c("Unboxing Weird Tech Gadgets", "Що подивитися на Netflix цього місяця", "How to Make a Short Film by Yourself", "Bible Explained in 30 Minutes", "Кулінарний влог: готуємо борщ", "Vlog: Hiking in the Alps", "Розпаковка AliExpress: смішні покупки", "The History of Ancient Rome in 10 Minutes", "Поради з тайм-менеджменту для студентів", "Як скласти ЗНО з математики на 200"),
  c("iPhone 15 Review: Is It Worth It?", "Біблія за 30 хвилин", "Як навчитися програмувати з нуля", "Кулінарний влог: готуємо борщ", "Morning Routine for Productivity", "How to Learn to Code from Scratch", "Огляд нового iPhone українською"),
  c("What to Watch on Netflix This Month", "Історія Київської Русі за 10 хвилин", "Кулінарний влог: готуємо борщ", "Interview with Elon Musk", "Як скласти ЗНО з математики на 200", "The History of Ancient Rome in 10 Minutes", "Поради з тайм-менеджменту для студентів"),
  c("Time Management for Students", "Як зняти короткометражний фільм самостійно", "The History of Ancient Rome in 10 Minutes", "Мотивація для ранкового бігу", "Top 10 Places to Visit in Europe", "Bible Explained in 30 Minutes", "Interview with Elon Musk", "Як навчитися програмувати з нуля"),
  c("Home Workout No Equipment", "Time Management for Students", "Кулінарний влог: готуємо борщ", "Top 10 Places to Visit in Europe", "Як навчитися програмувати з нуля", "How to Make a Short Film by Yourself", "Розпаковка AliExpress: смішні покупки", "Bible Explained in 30 Minutes", "Що подивитися на Netflix цього місяця", "Як скласти ЗНО з математики на 200"),
  c("Інтерв’ю з Іваном Марчуком", "Що подивитися на Netflix цього місяця", "The History of Ancient Rome in 10 Minutes", "How to Make a Short Film by Yourself", "Morning Routine for Productivity", "Біблія за 30 хвилин", "Як скласти ЗНО з математики на 200", "Top 10 Places to Visit in Europe"),
  c("ТОП-10 місць для відпочинку в Україні", "The History of Ancient Rome in 10 Minutes", "How to Learn to Code from Scratch", "Кулінарний влог: готуємо борщ", "Bible Explained in 30 Minutes", "Розпаковка AliExpress: смішні покупки", "Як зняти короткометражний фільм самостійно", "Vlog: Hiking in the Alps", "Top 10 Places to Visit in Europe"),
  c("Unboxing Weird Tech Gadgets", "Як навчитися програмувати з нуля", "Розпаковка AliExpress: смішні покупки", "Interview with Elon Musk", "Як зняти короткометражний фільм самостійно", "The History of Ancient Rome in 10 Minutes", "Time Management for Students"),
  c("Як зняти короткометражний фільм самостійно", "Cooking Vlog: Homemade Lasagna", "Top 10 Places to Visit in Europe", "Історія Київської Русі за 10 хвилин", "How to Learn to Code from Scratch", "Інтерв’ю з Іваном Марчуком", "Як скласти ЗНО з математики на 200"),
  c("Як зняти короткометражний фільм самостійно", "Влог з Карпат: піший похід", "How to Learn to Code from Scratch", "Bible Explained in 30 Minutes", "Розпаковка AliExpress: смішні покупки", "iPhone 15 Review: Is It Worth It?", "What to Watch on Netflix This Month", "Тренування вдома без обладнання", "Кулінарний влог: готуємо борщ", "Interview with Elon Musk"),
  c("Як навчитися програмувати з нуля", "What to Watch on Netflix This Month", "Cooking Vlog: Homemade Lasagna", "Vlog: Hiking in the Alps", "Біблія за 30 хвилин", "SAT Math Tips and Tricks", "Як зняти короткометражний фільм самостійно"),
  c("iPhone 15 Review: Is It Worth It?", "Влог з Карпат: піший похід", "Як зняти короткометражний фільм самостійно", "How to Learn to Code from Scratch", "ТОП-10 місць для відпочинку в Україні", "Time Management for Students", "Bible Explained in 30 Minutes"),
  c("ТОП-10 місць для відпочинку в Україні", "Огляд нового iPhone українською", "Interview with Elon Musk", "How to Make a Short Film by Yourself", "Morning Routine for Productivity", "Time Management for Students", "Vlog: Hiking in the Alps", "SAT Math Tips and Tricks", "Історія Київської Русі за 10 хвилин", "Кулінарний влог: готуємо борщ"),
  c("Біблія за 30 хвилин", "Cooking Vlog: Homemade Lasagna", "Unboxing Weird Tech Gadgets", "Що подивитися на Netflix цього місяця", "Top 10 Places to Visit in Europe", "The History of Ancient Rome in 10 Minutes", "Інтерв’ю з Іваном Марчуком", "Як зняти короткометражний фільм самостійно", "iPhone 15 Review: Is It Worth It?"),
  c("Як зняти короткометражний фільм самостійно", "SAT Math Tips and Tricks", "How to Learn to Code from Scratch", "The History of Ancient Rome in 10 Minutes", "Як скласти ЗНО з математики на 200", "Розпаковка AliExpress: смішні покупки", "Що подивитися на Netflix цього місяця", "How to Make a Short Film by Yourself", "Кулінарний влог: готуємо борщ", "Інтерв’ю з Іваном Марчуком"),
  c("Інтерв’ю з Іваном Марчуком", "Як скласти ЗНО з математики на 200", "How to Make a Short Film by Yourself", "Тренування вдома без обладнання", "The History of Ancient Rome in 10 Minutes", "Bible Explained in 30 Minutes", "iPhone 15 Review: Is It Worth It?", "Home Workout No Equipment", "Як зняти короткометражний фільм самостійно", "Як навчитися програмувати з нуля"),
  c("Огляд нового iPhone українською", "Top 10 Places to Visit in Europe", "Кулінарний влог: готуємо борщ", "How to Learn to Code from Scratch", "iPhone 15 Review: Is It Worth It?", "Розпаковка AliExpress: смішні покупки", "Як зняти короткометражний фільм самостійно", "Біблія за 30 хвилин", "Unboxing Weird Tech Gadgets"),
  c("Розпаковка AliExpress: смішні покупки", "Як навчитися програмувати з нуля", "The History of Ancient Rome in 10 Minutes", "Morning Routine for Productivity", "Тренування вдома без обладнання", "Vlog: Hiking in the Alps", "Як зняти короткометражний фільм самостійно"),
  c("Огляд нового iPhone українською", "Кулінарний влог: готуємо борщ", "Interview with Elon Musk", "The History of Ancient Rome in 10 Minutes", "Як навчитися програмувати з нуля", "Vlog: Hiking in the Alps", "Як зняти короткометражний фільм самостійно", "Top 10 Places to Visit in Europe", "Мотивація для ранкового бігу", "Що подивитися на Netflix цього місяця"),
  c("Bible Explained in 30 Minutes", "Як скласти ЗНО з математики на 200", "Історія Київської Русі за 10 хвилин", "Як навчитися програмувати з нуля", "Vlog: Hiking in the Alps", "How to Make a Short Film by Yourself", "What to Watch on Netflix This Month", "iPhone 15 Review: Is It Worth It?", "Тренування вдома без обладнання"),
  c("Поради з тайм-менеджменту для студентів", "Unboxing Weird Tech Gadgets", "Interview with Elon Musk", "Як зняти короткометражний фільм самостійно", "Біблія за 30 хвилин", "Time Management for Students", "SAT Math Tips and Tricks", "Home Workout No Equipment", "ТОП-10 місць для відпочинку в Україні"),
  c("Unboxing Weird Tech Gadgets", "Кулінарний влог: готуємо борщ", "Time Management for Students", "How to Learn to Code from Scratch", "iPhone 15 Review: Is It Worth It?", "ТОП-10 місць для відпочинку в Україні", "Інтерв’ю з Іваном Марчуком", "Поради з тайм-менеджменту для студентів", "Мотивація для ранкового бігу"),
  c("What to Watch on Netflix This Month", "The History of Ancient Rome in 10 Minutes", "Як зняти короткометражний фільм самостійно", "Top 10 Places to Visit in Europe", "Як навчитися програмувати з нуля", "How to Learn to Code from Scratch", "Interview with Elon Musk", "Розпаковка AliExpress: смішні покупки", "Vlog: Hiking in the Alps", "Як скласти ЗНО з математики на 200", "Біблія за 30 хвилин"),
  c("Time Management for Students", "Як зняти короткометражний фільм самостійно", "Як скласти ЗНО з математики на 200", "Біблія за 30 хвилин", "How to Learn to Code from Scratch", "Розпаковка AliExpress: смішні покупки", "Unboxing Weird Tech Gadgets", "Як навчитися програмувати з нуля", "Home Workout No Equipment"),
  c("Як зняти короткометражний фільм самостійно", "Як навчитися програмувати з нуля", "Огляд нового iPhone українською", "Unboxing Weird Tech Gadgets", "Як скласти ЗНО з математики на 200", "ТОП-10 місць для відпочинку в Україні", "How to Make a Short Film by Yourself", "Історія Київської Русі за 10 хвилин", "Home Workout No Equipment"),
  c("Як навчитися програмувати з нуля", "Мотивація для ранкового бігу", "Розпаковка AliExpress: смішні покупки", "Top 10 Places to Visit in Europe", "Interview with Elon Musk", "The History of Ancient Rome in 10 Minutes", "SAT Math Tips and Tricks", "Home Workout No Equipment", "Cooking Vlog: Homemade Lasagna"),
  c("Мотивація для ранкового бігу", "Unboxing Weird Tech Gadgets", "What to Watch on Netflix This Month", "The History of Ancient Rome in 10 Minutes", "How to Learn to Code from Scratch", "Розпаковка AliExpress: смішні покупки", "iPhone 15 Review: Is It Worth It?", "Interview with Elon Musk", "Time Management for Students", "Огляд нового iPhone українською", "SAT Math Tips and Tricks"),
  c("Як скласти ЗНО з математики на 200", "Біблія за 30 хвилин", "How to Learn to Code from Scratch", "Top 10 Places to Visit in Europe", "The History of Ancient Rome in 10 Minutes", "Як навчитися програмувати з нуля", "Історія Київської Русі за 10 хвилин", "Morning Routine for Productivity", "How to Make a Short Film by Yourself"),
  c("Як зняти короткометражний фільм самостійно", "The History of Ancient Rome in 10 Minutes", "Огляд нового iPhone українською", "Кулінарний влог: готуємо борщ", "Влог з Карпат: піший похід", "How to Make a Short Film by Yourself", "Тренування вдома без обладнання", "Біблія за 30 хвилин"),
  c("Історія Київської Русі за 10 хвилин", "How to Learn to Code from Scratch", "Як зняти короткометражний фільм самостійно", "Як навчитися програмувати з нуля", "Top 10 Places to Visit in Europe", "Cooking Vlog: Homemade Lasagna", "Unboxing Weird Tech Gadgets", "Біблія за 30 хвилин", "ТОП-10 місць для відпочинку в Україні"),
  c("What to Watch on Netflix This Month", "Cooking Vlog: Homemade Lasagna", "ТОП-10 місць для відпочинку в Україні", "Кулінарний влог: готуємо борщ", "Біблія за 30 хвилин", "Як зняти короткометражний фільм самостійно", "Як навчитися програмувати з нуля", "Top 10 Places to Visit in Europe", "The History of Ancient Rome in 10 Minutes", "Interview with Elon Musk"),
  c("Як навчитися програмувати з нуля", "Top 10 Places to Visit in Europe", "SAT Math Tips and Tricks", "Bible Explained in 30 Minutes", "Біблія за 30 хвилин", "Що подивитися на Netflix цього місяця", "Time Management for Students", "Cooking Vlog: Homemade Lasagna", "Unboxing Weird Tech Gadgets"),
  c("Як навчитися програмувати з нуля", "Як зняти короткометражний фільм самостійно", "Огляд нового iPhone українською", "Home Workout No Equipment", "How to Make a Short Film by Yourself", "Кулінарний влог: готуємо борщ", "Мотивація для ранкового бігу", "Time Management for Students", "Розпаковка AliExpress: смішні покупки", "Тренування вдома без обладнання", "Що подивитися на Netflix цього місяця"),
  c("Біблія за 30 хвилин", "Розпаковка AliExpress: смішні покупки", "How to Make a Short Film by Yourself", "Що подивитися на Netflix цього місяця", "Top 10 Places to Visit in Europe", "Bible Explained in 30 Minutes", "Vlog: Hiking in the Alps", "Як скласти ЗНО з математики на 200", "Cooking Vlog: Homemade Lasagna"),
  c("Що подивитися на Netflix цього місяця", "Розпаковка AliExpress: смішні покупки", "Кулінарний влог: готуємо борщ", "The History of Ancient Rome in 10 Minutes", "Мотивація для ранкового бігу", "Top 10 Places to Visit in Europe", "Як навчитися програмувати з нуля", "SAT Math Tips and Tricks", "Біблія за 30 хвилин"),
  c("Interview with Elon Musk", "Огляд нового iPhone українською", "Як зняти короткометражний фільм самостійно", "Vlog: Hiking in the Alps", "Біблія за 30 хвилин", "What to Watch on Netflix This Month", "Мотивація для ранкового бігу"),
  c("Time Management for Students", "How to Make a Short Film by Yourself", "Влог з Карпат: піший похід", "Як навчитися програмувати з нуля", "Як зняти короткометражний фільм самостійно", "Top 10 Places to Visit in Europe", "Unboxing Weird Tech Gadgets", "Тренування вдома без обладнання", "Cooking Vlog: Homemade Lasagna"),
  c("Top 10 Places to Visit in Europe", "Cooking Vlog: Homemade Lasagna", "SAT Math Tips and Tricks", "Як зняти короткометражний фільм самостійно", "Як скласти ЗНО з математики на 200", "Bible Explained in 30 Minutes", "Історія Київської Русі за 10 хвилин", "Кулінарний влог: готуємо борщ", "Інтерв’ю з Іваном Марчуком"),
  c("Morning Routine for Productivity", "Time Management for Students", "Як навчитися програмувати з нуля", "How to Make a Short Film by Yourself", "Cooking Vlog: Homemade Lasagna", "Тренування вдома без обладнання", "iPhone 15 Review: Is It Worth It?", "Інтерв’ю з Іваном Марчуком", "Як зняти короткометражний фільм самостійно", "ТОП-10 місць для відпочинку в Україні"),
  c("Home Workout No Equipment", "The History of Ancient Rome in 10 Minutes", "Як скласти ЗНО з математики на 200", "Інтерв’ю з Іваном Марчуком", "Top 10 Places to Visit in Europe", "Як зняти короткометражний фільм самостійно", "Interview with Elon Musk", "iPhone 15 Review: Is It Worth It?", "Розпаковка AliExpress: смішні покупки"),
  c("Історія Київської Русі за 10 хвилин", "Як навчитися програмувати з нуля", "Мотивація для ранкового бігу", "Кулінарний влог: готуємо борщ", "Що подивитися на Netflix цього місяця", "Home Workout No Equipment", "How to Learn to Code from Scratch", "Розпаковка AliExpress: смішні покупки", "Влог з Карпат: піший похід"),
  c("Поради з тайм-менеджменту для студентів", "Як зняти короткометражний фільм самостійно", "Як скласти ЗНО з математики на 200", "Кулінарний влог: готуємо борщ", "Біблія за 30 хвилин", "Розпаковка AliExpress: смішні покупки", "The History of Ancient Rome in 10 Minutes", "SAT Math Tips and Tricks", "Як навчитися програмувати з нуля"),
  c("iPhone 15 Review: Is It Worth It?", "Поради з тайм-менеджменту для студентів", "Як зняти короткометражний фільм самостійно", "How to Learn to Code from Scratch", "How to Make a Short Film by Yourself", "Cooking Vlog: Homemade Lasagna", "Розпаковка AliExpress: смішні покупки", "Мотивація для ранкового бігу", "Interview with Elon Musk", "Інтерв’ю з Іваном Марчуком", "Home Workout No Equipment"),
  c("Як навчитися програмувати з нуля", "How to Learn to Code from Scratch", "Розпаковка AliExpress: смішні покупки", "Cooking Vlog: Homemade Lasagna", "Біблія за 30 хвилин", "Як зняти короткометражний фільм самостійно", "The History of Ancient Rome in 10 Minutes", "Vlog: Hiking in the Alps", "Unboxing Weird Tech Gadgets", "iPhone 15 Review: Is It Worth It?"),
  c("How to Learn to Code from Scratch", "Що подивитися на Netflix цього місяця", "SAT Math Tips and Tricks", "Як зняти короткометражний фільм самостійно", "Розпаковка AliExpress: смішні покупки", "Як скласти ЗНО з математики на 200", "Біблія за 30 хвилин", "Time Management for Students", "Як навчитися програмувати з нуля"),
  c("ТОП-10 місць для відпочинку в Україні", "How to Make a Short Film by Yourself", "What to Watch on Netflix This Month", "Кулінарний влог: готуємо борщ", "Як зняти короткометражний фільм самостійно", "Vlog: Hiking in the Alps", "Розпаковка AliExpress: смішні покупки"),
  c("Біблія за 30 хвилин", "The History of Ancient Rome in 10 Minutes", "Unboxing Weird Tech Gadgets", "Тренування вдома без обладнання", "Top 10 Places to Visit in Europe", "Огляд нового iPhone українською", "iPhone 15 Review: Is It Worth It?", "Як скласти ЗНО з математики на 200"),
  c("The History of Ancient Rome in 10 Minutes", "Влог з Карпат: піший похід", "SAT Math Tips and Tricks", "Interview with Elon Musk", "Home Workout No Equipment", "Як скласти ЗНО з математики на 200", "Як зняти короткометражний фільм самостійно", "Bible Explained in 30 Minutes", "Кулінарний влог: готуємо борщ", "ТОП-10 місць для відпочинку в Україні")
)

# Перетворення списку в об'єкт транзакцій, необхідний для аналізу асоціативних правил
trans <- as(youtube_views, "transactions")

# Виведення розмірності об'єкта транзакцій: кількість транзакцій (рядків) та кількість унікальних елементів (стовпців)
dim(trans)

# Повернення множини унікальних елементів (назв відео), які присутні у транзакціях
itemLabels(trans)

# Виведення розгорнутого підсумку об'єкта транзакцій, включаючи частоту найпоширеніших елементів та розподіл довжини транзакцій
summary(trans)

# Візуалізація матриці транзакцій, де рядки - транзакції, стовпці - елементи, а зафарбовані клітинки вказують на присутність елемента в транзакції
image(trans)

# Побудова графіку частоти зустрічальності топ-5 найпопулярніших відео
itemFrequencyPlot(trans, topN=5,  cex.names=1)

# Застосування алгоритму Apriori для видобутку асоціативних правил з заданими параметрами
# Вибір значення supp та conf я робив на основі медіани всіх значень support та confidence з команди "summary(rules)" без попереднього обмеження цих значень в команді apriori
rules <- apriori(trans,
                 parameter = list(supp=0.1324, conf=0.3750,
                                  maxlen=10,
                                  target= "rules"))

# Виведення підсумкової інформації про знайдені асоціативні правила, включаючи кількість правил та їхні характеристики
summary(rules)

# Перегляд знайдених асоціативних правил у текстовому форматі, включаючи support, confidence та lift
inspect(rules)

# Візуалізація знайдених асоціативних правил за допомогою стандартного графіка розсіювання, де вісь x представляє support, а вісь y - confidence
plot(rules)

# Візуалізація асоціативних правил, де обидві вісі представляють confidence
plot(rules, measure = "confidence")

# Візуалізація асоціативних правил за допомогою двовимірного графіка ключів (support та confidence)
plot(rules, method = "two-key plot")

# Інтерактивна візуалізація асоціативних правил за допомогою бібліотеки plotly (моя субʼєктивна думка: це найкращий engine на пару з "htmlwidget")
plot(rules, engine = "plotly")

# Вибір топ-10 правил за показником confidence
subrules <- head(rules, n = 10, by = "confidence")

# Візуалізація топ-10 правил у вигляді графа, використовуючи htmlwidget для інтерактивності
plot(subrules, method = "graph",  engine = "htmlwidget")

# Візуалізація топ-10 правил за допомогою паралельних координат
plot(subrules, method="paracoord")


# Видобуток асоціативних правил, які мають "Кулінарний влог: готуємо борщ" у правій частині (RHS)
cooking_rules_rhs <- apriori(trans,
                             parameter = list(supp=0.1324, conf=0.3750,
                                              maxlen=10,
                                              minlen=2),
                             appearance = list(default="lhs", rhs="Кулінарний влог: готуємо борщ"))

# Перегляд асоціативних правил, де "Кулінарний влог: готуємо борщ" є наслідком
inspect(cooking_rules_rhs)


# Видобуток асоціативних правил, які мають "Кулінарний влог: готуємо борщ" у лівій частині (LHS)
cooking_rules_lhs <- apriori(trans, parameter=list(supp=0.1324, conf=0.3750,
                                                   maxlen=10,
                                                   minlen=2),
                             appearance = list(lhs="Кулінарний влог: готуємо борщ", default="rhs"))


# Перегляд асоціативних правил, де "Кулінарний влог: готуємо борщ" є передумовою
inspect(cooking_rules_lhs)

# Візуалізація асоціативних правил, де "Кулінарний влог: готуємо борщ" є наслідком
plot(cooking_rules_rhs)



# Висновки:

# 1. Розмірність транзакцій:
#    - Кількість транзакцій (переглядів користувачів): 204
#    - Кількість унікальних відео: 30

# 2. Найчастіші відео:
#    - "Як зняти короткометражний фільм самостійно" є найпопулярнішим відео (109 переглядів).
#    - "Як навчитися програмувати з нуля" також дуже популярне (100 переглядів).
#    - "The History of Ancient Rome in 10 Minutes", "Як скласти ЗНО з математики на 200" та "Кулінарний влог: готуємо борщ" входять до топ-5.

# 3. Довжина транзакцій:
#    - Більшість користувачів переглядають від 8 до 10 різних відео за сесію.
#    - Середня кількість переглянутих відео за сесію становить приблизно 8.8.

# 4. Знайдені асоціативні правила (загальні):
#    - Було знайдено 70 асоціативних правил, що задовольняють заданим критеріям support (0.1324) та confidence (0.3750).
#    - Більшість правил складаються з одного antecedent та одного consequent.
#    - Правила з порожньою лівою частиною (порожнім antecedent) показують загальну популярність окремих відео. 
#      Наприклад, правило {} => {Як зняти короткометражний фільм самостійно} має $confidence$ 0.534, що підтверджує його високу популярність.

# 5. Топ-10 правил за confidence:
#    - Найвищу confidence мають правила, де перегляд певного відео сильно корелює з переглядом іншого. 
#      Наприклад, {iPhone 15 Review: Is It Worth It?} => {Як зняти короткометражний фільм самостійно} має confidence 0.617, що означає, що користувачі, які дивилися огляд iPhone 15, часто також дивляться відео про створення короткометражних фільмів.

# 6. Правила, пов'язані з "Кулінарний влог: готуємо борщ" (consequent):
#    - Користувачі, які дивилися "Time Management for Students", "How to Learn to Code from Scratch", "Як скласти ЗНО з математики на 200" або "The History of Ancient Rome in 10 Minutes", також часто дивляться "Кулінарний влог: готуємо борщ".
#    - Правило {Як зняти короткометражний фільм самостійно} => {Кулінарний влог: готуємо борщ} має відносно високий support (0.206), 
#      але нижчий confidence (0.385), що свідчить про те, що хоча багато хто дивиться обидва відео, перегляд відео про короткометражні фільми не є сильним предиктором перегляду кулінарного влогу.

# 7. Правила, пов'язані з "Кулінарний влог: готуємо борщ" (antecedent):
#    - Користувачі, які дивилися "Кулінарний влог: готуємо борщ", також часто цікавляться відео 
#       "How to Learn to Code from Scratch", 
#       "Як скласти ЗНО з математики на 200", 
#       "The History of Ancient Rome in 10 Minutes", 
#       "Як навчитися програмувати з нуля" 
#       та "Як зняти короткометражний фільм самостійно".

# Загальний висновок: Аналіз асоціативних правил виявив цікаві закономірності у переглядах відео.
# Наприклад, існує зв'язок між навчальними відео ("Як навчитися програмувати з нуля", "Як скласти ЗНО з математики на 200", "Time Management for Students") 
# та іншими типами контенту, такими як кулінарні влоги та відео про створення фільмів. Це може бути корисним для рекомендаційних систем YouTube.


